(defun divisible (a b) (mod a b))
(defvar x 0)
(defvar y 0)
(defvar startval 999999)
(defvar maxcount 0)
(defvar longstart 0)
(loop
(setq x startval)
(setq y 0)
(loop 
  (if (= (divisible x 2) 0)(setq x (/ x 2)) 
    (setq x (+ (* 3 x ) 1 )))
	(setq y (+ y 1))
	(when (<= x 1) (return x))
	)
	(if (<= maxcount y) (setq maxcount y))
	(if (<= maxcount y) (setq longstart startval))
	(setq startval (- startval 1))
	(when (<= startval 1) (return longstart))
	)
(write longstart)
